# Generated by Django 5.2 on 2025-04-22 17:23

import AIPredict.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIPredict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepdata',
            name='timestamp',
            field=models.DateTimeField(default=AIPredict.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='start_time',
            field=models.DateTimeField(default=AIPredict.models.get_current_time),
        ),
    ]
