# Generated by Django 5.2 on 2025-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heartRate', models.FloatField()),
                ('spo2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('is_fall', models.BooleanField(default=False)),
                ('is_abnormal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
