# Generated by Django 5.2 on 2025-04-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heartRate', models.FloatField()),
                ('spo2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('is_fall', models.BooleanField(default=False)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('sample_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameModel(
            old_name='SensorData',
            new_name='RawSensorData',
        ),
    ]
