# Generated by Django 5.2 on 2025-04-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_aggregatedsensordata_rename_sensordata_rawsensordata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawSensorData',
            new_name='SensorData',
        ),
        migrations.DeleteModel(
            name='AggregatedSensorData',
        ),
    ]
