# Generated by Django 5.2 on 2025-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_rawsensordata_sensordata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mqtt_broker', models.CharField(default='0f6bce09467e483792a9cc8f3c79ab5f.s1.eu.hivemq.cloud', max_length=255)),
                ('mqtt_port', models.IntegerField(default=8883)),
                ('mqtt_topic', models.CharField(default='sensor/data', max_length=255)),
                ('mqtt_username', models.CharField(default='hoan1234', max_length=255)),
                ('mqtt_password', models.CharField(default='Hoan1234', max_length=255)),
                ('heart_rate_min', models.FloatField(default=80)),
                ('heart_rate_max', models.FloatField(default=105)),
                ('spo2_min', models.FloatField(default=95)),
                ('temperature_min', models.FloatField(default=30)),
                ('temperature_max', models.FloatField(default=37)),
                ('acceleration_min', models.FloatField(default=0.5)),
                ('acceleration_max', models.FloatField(default=1.5)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
