# Generated by Django 5.2 on 2025-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('quality', models.CharField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BAD', 'Bad')], max_length=20)),
                ('total_duration', models.DurationField()),
                ('deep_sleep_duration', models.DurationField()),
                ('light_sleep_duration', models.DurationField()),
                ('wake_duration', models.DurationField()),
                ('avg_acceleration', models.FloatField(help_text='Average acceleration during sleep')),
                ('movement_count', models.IntegerField(help_text='Number of significant movements detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={},
        ),
    ]
