# Generated by Django 5.2 on 2025-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_sleepsession_alter_sensordata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SleepSession',
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='acceleration_max',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='acceleration_min',
        ),
        migrations.AddField(
            model_name='settings',
            name='acceleration_threshold',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heart_rate_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heart_rate_min',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_broker',
            field=models.CharField(default='localhost', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_port',
            field=models.IntegerField(default=1883),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='spo2_min',
            field=models.IntegerField(default=95),
        ),
    ]
