# Generated by Django 5.2 on 2025-04-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_emailnotification_delete_sleepsession_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='acceleration_threshold',
        ),
        migrations.AddField(
            model_name='settings',
            name='acceleration_max',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='settings',
            name='acceleration_min',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heart_rate_max',
            field=models.FloatField(default=105),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heart_rate_min',
            field=models.FloatField(default=80),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_broker',
            field=models.CharField(default='0f6bce09467e483792a9cc8f3c79ab5f.s1.eu.hivemq.cloud', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_password',
            field=models.CharField(default='Hoan1234', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_port',
            field=models.IntegerField(default=8883),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_username',
            field=models.CharField(default='hoan1234', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='spo2_min',
            field=models.FloatField(default=95),
        ),
    ]
