# Generated by Django 5.2 on 2025-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_emailnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email_list',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='acceleration_max',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heart_rate_max',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heart_rate_min',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_broker',
            field=models.CharField(default='broker.hivemq.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_port',
            field=models.IntegerField(default=1883),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
